name: Node.js CI
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: NPM Install and Build
        run: |
          npm install
          npm run build
          
      - uses: actions/upload-artifact@main
        with:
          name: gamneArtifact
          path: public/
          
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@main
        with: 
          name: gamneArtifact
          path: public

      - name: Test using Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Install and Build For TEST
        run: |
          npm install
          npm test
        env:
          CI: true
