name: Node.js CI
on: [push] # only trigger on push
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: NPM Install and Build
        run: |
          npm install
          npm run build
        
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x] # P001 2021-07-26 AH - Enhance to use 12 and 14 only (removed 16)
        os: [ubuntu-latest, windows-latest] # P002 2021-07-26 AH - Build for Ubuntu and Windows
    steps:
      - uses: actions/checkout@v2
      - name: Test using Node.js ${{ matrix.node-version }} # each of the versions specified under node-version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Install and Build For TEST
        run: |
          npm ci
          npm run build --if-present
          npm test
        env:
          CI: true # continuous integration
